{
 "title": "Forcepoint",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Forcepoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Evénements récents",
   "type": "stat",
   "description": "Affiche le nombre total des événements enregistrés depuis la dernière heure.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forcepoint_total_event{nombre_event=\"1h\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre d'événements",
   "type": "timeseries",
   "description": "Timeline du nombre d'événements enregistrés depuis la dernière heure.",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "forcepoint_total_event{nombre_event=\"1h\", job=\"forcepoint\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Détails des événements",
   "type": "table",
   "description": "Triés par date (de la plus récente à la plus ancienne).",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "forcepoint_priority_event{job=\"forcepoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Liens vers l'événement",
   "type": "table",
   "description": "Lien URL vers l'événement associé.",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "forcepoint_priority_event{job=\"forcepoint\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}